test:
  script:
  - apt-get update -qy
  - apt-get install -y mlocate cpio
  - apt-get install -y gfortran
  - apt-get install -y swig
  - apt-get install -y python3 python3-dev python3-numpy python3-libxml2
  - python3 --version
  - cd metro
  - ./init_devel.sh
  - cd src/model
  - ../../scripts/do_macadam
  - cd ../frontend/../../metro/usr/share/metro/data/test_suite
  - python3 test_suite.py
  
